import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Turborepo",
	description: "Generated by create turbo",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}): JSX.Element {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div>
					<ul>
						<li>
							<Link href={"/"}>home Page</Link>
						</li>
						<li>
							<Link href={"/auth"}>auth page</Link>
						</li>
					</ul>
				</div>
				{children}
			</body>
		</html>
	);
}
